filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: mqtt
  hosts: 
    - tcp://rabbitmq:1883
  topics: 
    - amq/topic

output.elasticsearch.ssl.verification_mode: none
output.elasticsearch.hosts: ['http://elasticsearch:9200']
output.elasticsearch.username: 'elastic'
output.elasticsearch.password: 'elastic'
output.elasticsearch.pipeline: 'parse_json'
output.elasticsearch.index: "%{[fields.log_type]}-%{[agent.version]}-%{+yyyy.MM.dd}"
