using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace BlazorAbbPoc.Shared.Plc;

public class AbbPlcMsg
{
    public string? deviceId { get; set; }
    public int commands { get; set; }
    public int ctw { get; set; }
    public int nrCbOperation { get; set; }
    public int nrCbManOpen { get; set; }
    public int nrCbProtectTrips { get; set; }
    public int nrCbProtectTripFails { get; set; }
    public int nrCbProtectTripTests { get; set; }
    public int ProgramFailError { get; set; }
    public int l1A { get; set; }
    public int l2A { get; set; }
    public int l3A { get; set; }
    public int NeA { get; set; }
    public int IntgndA { get; set; }
    public int ExtgndRcA { get; set; }
    public int l1nV { get; set; }
    public int l2nV { get; set; }
    public int l3nV { get; set; }
    public int l1l2V { get; set; }
    public int l2l3V { get; set; }
    public int l3l1V { get; set; }
    public int pActL1 { get; set; }
    public int pActL2 { get; set; }
    public int pActL3 { get; set; }
    public int pActTotal { get; set; }
    public int pReactL1 { get; set; }
    public int pReactL2 { get; set; }
    public int pReactL3 { get; set; }
    public int pReactTotal { get; set; }
    public int pAppL1 { get; set; }
    public int pAppL2 { get; set; }
    public int pAppL3 { get; set; }
    public int pAppTotal { get; set; }
    public int pfL1 { get; set; }
    public int pfL2 { get; set; }
    public int pfL3 { get; set; }
    public int pfTotal { get; set; }
    public int frq { get; set; }
    public int load049In { get; set; }
    public int load5079In { get; set; }
    public int load7989In { get; set; }
    public int loadProfile90In { get; set; }
    public int actEnergyPos { get; set; }
    public int actEnergyNeg { get; set; }
    public int actEnergyTot { get; set; }
    public int reactEnergyPos { get; set; }
    public int reactEnergyNeg { get; set; }
    public int reactEnergyTot { get; set; }
    public int appEnergyTot { get; set; }
    public int energyStorTime { get; set; }
    public int totHarmDist { get; set; }
    public int _1Harm { get; set; }
    public int _2Harm { get; set; }
    public int _3Harm { get; set; }
    public int _4Harm { get; set; }
    public int _5Harm { get; set; }
    public int _6Harm { get; set; }
    public int _7Harm { get; set; }
    public int _8Harm { get; set; }
    public int _9Harm { get; set; }
    public int _10Harm { get; set; }
    public int _11Harm { get; set; }
    public int _12Harm { get; set; }
    public int _13Harm { get; set; }
    public int _14Harm { get; set; }
    public int _15Harm { get; set; }
    public int _16Harm { get; set; }
    public int _17Harm { get; set; }
    public int _18Harm { get; set; }
    public int _19Harm { get; set; }
    public int _20Harm { get; set; }
    public int _21Harm { get; set; }
    public int _22Harm { get; set; }
    public int _23Harm { get; set; }
    public int _24Harm { get; set; }
    public int _25Harm { get; set; }
    public int _26Harm { get; set; }
    public int _27Harm { get; set; }
    public int _28Harm { get; set; }
    public int _29Harm { get; set; }
    public int _30Harm { get; set; }
    public int _31Harm { get; set; }
    public int _32Harm { get; set; }
    public int _33Harm { get; set; }
    public int _34Harm { get; set; }
    public int _35Harm { get; set; }
    public int _36Harm { get; set; }
    public int _37Harm { get; set; }
    public int _38Harm { get; set; }
    public int _39Harm { get; set; }
    public int _40Harm { get; set; }
    public int _41Harm { get; set; }
    public int _42Harm { get; set; }
    public int _43Harm { get; set; }
    public int _44Harm { get; set; }
    public int _45Harm { get; set; }
    public int _46Harm { get; set; }
    public int _47Harm { get; set; }
    public int _48Harm { get; set; }
    public int _49Harm { get; set; }
    public int _50Harm { get; set; }
    public int protA_L_Config { get; set; }
    public int ProtA_L_I1 { get; set; }
    public int ProtA_L_t1 { get; set; }
    public int ProtA_L_Curve { get; set; }
    public int ProtA_L_PrealarmI1 { get; set; }
    public int ProtA_S_Config { get; set; }
    public int ProtA_S_I2 { get; set; }
    public int ProtA_S_t2 { get; set; }
    public int ProtA_S_I22 { get; set; }
    public int ProtA_S_t22 { get; set; }
    public int ProtA_S_Curve { get; set; }
    public int ProtA_S_ZoneSelectT { get; set; }
    public int ProtA_I_Config { get; set; }
    public int ProtA_I_I3 { get; set; }
    public int ProtB_L_Config { get; set; }
    public int ProtB_L_I1 { get; set; }
    public int ProtB_L_t1 { get; set; }
    public int ProtB_L_Curve { get; set; }
    public int ProtB_L_PrealarmI1 { get; set; }
    public int ProtB_S_Config { get; set; }
    public int ProtB_S_I2 { get; set; }
    public int ProtB_S_t2 { get; set; }
    public int ProtB_S_I22 { get; set; }
    public int ProtB_S_t22 { get; set; }
    public int ProtB_S_Curve { get; set; }
    public int ProtB_S_ZoneSelectT { get; set; }
    public int ProtB_I_Config { get; set; }
    public int ProtB_I_I3 { get; set; }
    public string? timestamp { get; set; }
    public string? alarm1 { get; set; }
    public string? alarm2 { get; set; }
    public float rms1 { get; set; }
}
